// Canonical Parquet schema descriptor — kept byte-identical with the Go side
// (`golang/cli/trace_compact.go`'s `traceSchemaCanonical()`). The hash of this
// string is asserted on both sides; if either drifts, both tests fail and both
// must be updated in lockstep.
//
// Format key: `name:type[?]` for nullable columns, semicolon-separated. The
// types are the on-disk Arrow types, not Parquet logical types — `u64`,
// `u16`, `binary?`. Keep this in sync with `TraceParquetSchema` in the Go
// compactor and the column order matters for the hash.
export const TRACE_SCHEMA_CANONICAL =
  "i:u64;t:u64;op:u16;fault_bits:u64;inv_fired_bits:u64;inv_violated_bits:u64;writes_json:binary?";

// Pinned SHA-256 of TRACE_SCHEMA_CANONICAL. Generated by the Go side and
// asserted here; the schema-sync test on each side re-derives the hash and
// fails if either drifts. To change the schema:
//   1. Update TraceParquetSchema in golang/cli/trace_compact.go
//   2. Update traceSchemaCanonical() in the same file
//   3. Update TRACE_SCHEMA_CANONICAL here
//   4. Run `go test ./cli/... -run TestSchemaHashStable` to get the new hash
//   5. Paste it into both `want` constants (Go and TS) below
export const TRACE_SCHEMA_HASH =
  "9b32f8790ba262c906ab5fa51b88c20d4459729a35e8d0e8a983d2227de7943f";

/**
 * traceSchemaHash returns the SHA-256 of TRACE_SCHEMA_CANONICAL using SubtleCrypto
 * (browser + Node ≥ 19). Async because that's what Web Crypto exposes; both the
 * schema-sync test and any runtime sanity check await it.
 */
export async function traceSchemaHash(): Promise<string> {
  const bytes = new TextEncoder().encode(TRACE_SCHEMA_CANONICAL);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const hex = Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return hex;
}
